### ISSUE TITLE
In ClassDiagramBuilder.php line 74: Class "XXX" does not exist 

### ISSUE THREAD

**Issue by MetalArend** [llaville/umlwriter#23]
I have been looking into this project for a few days now, trying to use it as a Docker image, but I'm getting lost in the documentation: the umlwriter repository mentions the graph-uml in the Credits of the README - but that's another repository. It also talks about using the box-manifest, also another repository. 

When I tried to run it after building the phar, it fails on loading one of the classes of the project I'm trying to scan, as if something is wrong with the autoloading.

This is what I figured out so far:

## A multi stage Dockerfile to use git, composer and box to create the umlwriter phar file.

```Dockerfile
FROM composer:2.3.7 as composer

FROM ghcr.io/llaville/box-manifest:latest as phar-builder
WORKDIR /app
RUN apk update && apk add git
RUN git clone -b 3.x https://github.com/llaville/umlwriter.git .
COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN /usr/bin/composer install
RUN /usr/local/src/box-manifest/bin/box compile

FROM php:8.1-fpm
COPY --from=phar-builder /app/bin/umlwriter.phar /usr/local/bin/umlwriter
RUN chmod +x /usr/local/bin/umlwriter
CMD [ 'umlwriter' ]
```

A small makefile to build and run the image based on that file.

```
build:
	docker build --tag uml:latest .

run:
	docker run --rm --interactive --tty \
		--name uml \
		--volume "$$(cd ../project && pwd):/app" \
		--workdir "/app" \
		uml:latest umlwriter -vvv diagram:class src/ --generator graphviz

bash:
	docker run --rm --interactive --tty --name uml uml:latest bash
```

This shows me the correct header:

```
UML Class Diagram Generation
============================

 --------------- ---------------------------------------------- 
  Path(s)         src/                                          
  Generator       graphviz                                      
  Configuration   Default values and/or command line arguments  
 --------------- ---------------------------------------------- 
```

followed by an error on one of the classes inside the project in the /app directory:

```
In ClassDiagramBuilder.php line 74:
                                                                                                       
  [ReflectionException (-1)]                                                                           
  Class "XXX" does not exist  
                                                                                                       
Exception trace:
  at phar:///usr/local/bin/umlwriter/vendor/bartlett/graph-uml/src/ClassDiagramBuilder.php:74
 ReflectionClass->__construct() at phar:///usr/local/bin/umlwriter/vendor/bartlett/graph-uml/src/ClassDiagramBuilder.php:74
 Bartlett\GraphUml\ClassDiagramBuilder->createVertexClass() at phar:///usr/local/bin/umlwriter/src/Service/ClassDiagramRenderer.php:62
 Bartlett\UmlWriter\Service\ClassDiagramRenderer->__invoke() at phar:///usr/local/bin/umlwriter/src/Console/Command/ClassDiagramCommand.php:120
 Bartlett\UmlWriter\Console\Command\ClassDiagramCommand->execute() at phar:///usr/local/bin/umlwriter/vendor/symfony/console/Command/Command.php:291
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/umlwriter/vendor/symfony/console/Application.php:998
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/umlwriter/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/umlwriter/src/Console/Application.php:93
 Bartlett\UmlWriter\Console\Application->doRun() at phar:///usr/local/bin/umlwriter/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/umlwriter/src/Console/Application.php:124
 Bartlett\UmlWriter\Console\Application->run() at phar:///usr/local/bin/umlwriter/bin/umlwriter:52
 require() at /usr/local/bin/umlwriter:14

diagram:class [-o|--output OUTPUT] [--format FORMAT] [--generator GENERATOR] [--bootstrap BOOTSTRAP] [-c|--configuration CONFIGURATION] [--without-constants] [--without-properties] [--without-methods] [--hide-private] [--hide-protected] [--no-statement] [--] [<paths>...]

make: *** [makefile:5: use] Error 1

```

I checked to see if the vendor directory in the project was correctly created by composer, and it was. Is there something I'm forgetting here?

**Comment by MetalArend** [comment]
I tried to simplify the setup a bit. I think what was meant in the documentation, is that box is not supposed to be loaded as a composer dependency, right? It's not about umlwriter, right? Trying to figure out the documentation a bit further.

So I created another Dockerfile:

```
FROM php:8.0-fpm
RUN apt-get update && apt-get install -y git graphviz openjdk-11-jre-headless zip
COPY --from=composer:2.3.7 /usr/bin/composer /usr/bin/composer
RUN composer global config minimum-stability dev
RUN composer global config --no-plugins allow-plugins.cweagans/composer-patches true
RUN composer global require bartlett/umlwriter:^3.0
ENV PATH=${PATH}:/root/.composer/vendor/bin
CMD [ 'umlwriter' ]
```

and updated the makefile to use the `--bootstrap` flag, to load the `autoload.php` from my project:

```
build:
	docker build --tag uml:latest .

run:
	docker run --rm --interactive --tty \
		--name uml \
		--volume "$$(cd ../project && pwd):/app" \
		--workdir "/app" \
		uml:latest umlwriter -vvv diagram:class src/ \
		--bootstrap vendor/autoload.php \
		--generator graphviz

bash:
	docker run --rm --interactive --tty --name uml uml:latest bash
```

Now the output/error changed to:

```

UML Class Diagram Generation
============================


Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Console\Helper\Helper::strlenWithoutDecoration() in /app/vendor/symfony/console/Helper/Table.php:788
Stack trace:
#0 /app/vendor/symfony/console/Helper/Table.php(770): Symfony\Component\Console\Helper\Table->getCellWidth(Array, 0)
#1 /app/vendor/symfony/console/Helper/Table.php(361): Symfony\Component\Console\Helper\Table->calculateColumnsWidth(Object(Symfony\Component\Console\Helper\TableRows))
#2 /root/.composer/vendor/symfony/console/Style/SymfonyStyle.php(203): Symfony\Component\Console\Helper\Table->render()
#3 /root/.composer/vendor/symfony/console/Style/SymfonyStyle.php(239): Symfony\Component\Console\Style\SymfonyStyle->horizontalTable(Array, Array)
#4 /root/.composer/vendor/bartlett/umlwriter/src/Console/Command/ClassDiagramCommand.php(116): Symfony\Component\Console\Style\SymfonyStyle->definitionList(Array, Array, Array)
#5 /root/.composer/vendor/symfony/console/Command/Command.php(291): Bartlett\UmlWriter\Console\Command\ClassDiagramCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /root/.composer/vendor/symfony/console/Application.php(1002): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /root/.composer/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Bartlett\UmlWriter\Console\Command\ClassDiagramCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /root/.composer/vendor/bartlett/umlwriter/src/Console/Application.php(93): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /root/.composer/vendor/symfony/console/Application.php(171): Bartlett\UmlWriter\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /root/.composer/vendor/bartlett/umlwriter/src/Console/Application.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /root/.composer/vendor/bartlett/umlwriter/bin/umlwriter(53): Bartlett\UmlWriter\Console\Application->run()
#12 /root/.composer/vendor/bin/umlwriter(120): include('/root/.composer...')
#13 {main}
  thrown in /app/vendor/symfony/console/Helper/Table.php on line 788
make: *** [makefile:5: run] Error 255
```

**Comment by judgej** [comment]
Also having this problem, and very confused by the documentation. It is not at all clear how this package/tool is supposed to be used.

**Comment by llaville** [comment]
@judgej If you've problems to read Material for MkDocs target output, I suggest you to read raw files in `docs` folder of this repository.

**Comment by llaville** [comment]
@MetalArend Could you send the list of Composer dependencies used to build your Docker version. A docker build result will be appreciated to know what versions are really used.
And If your source code analysed is open sourced, please provide URL of the repository to help to reproduced issue

**Comment by MetalArend** [comment]
As I was writing a response, I figured I could test some things out first in the direction you were pointing me, to make it easier, instead of giving you a list from `composer show` with 150 exact versions :see_no_evil: . I narrowed it down to:

```
symfony/console:v5.2.14
```

The source code I was trying this against, is not open source. One of the few. But if you create the project directory (mentioned in the makefile as docker volume mapped to /app), and run `composer init` and `composer require symfony/console:v5.2.14`, and then run `make run`, things fail with the exact error mentioned above.

I'm not sure if this is what I would expect from a tool, using my project's dependencies instead of the tool's own dependencies?

**Comment by llaville** [comment]
I cannot reproduced your error, especially on PHP 8.0 platform.

Here is my use case:  
- `PHP` 8.0.23
- `bartlett/umlwriter` 3.2.0

Dependencies installed are (checked with `composer show` command and Composer 2.4.1) : 
```
bartlett/graph-plantuml-generator 1.2.1              A PlantUML generator for graph-uml
bartlett/graph-uml                1.2.2              PHP library which helps you build UML diagrams.
cweagans/composer-patches         1.7.2              Provides a way to patch Composer packages.
graphp/graph                      dev-master 04461a7 GraPHP is the mathematical graph/network library written in PHP.
graphp/graphviz                   dev-master 5872f6b GraphViz graph drawing for the mathematical graph/network library GraPHP.
jawira/plantuml                   v1.2022.7          Provides PlantUML executable and plantuml.jar
jawira/plantuml-encoding          v1.1.0             PlantUML encoding functions
jetbrains/phpstorm-stubs          v2022.2            PHP runtime & extensions header files for PhpStorm
nikic/php-parser                  v4.15.1            A PHP parser written in PHP
psr/container                     1.1.2              Common Container Interface (PHP FIG PSR-11)
roave/better-reflection           5.9.0              Better Reflection - an improved code reflection API
roave/signature                   1.6.0              Sign and verify stuff
symfony/config                    v6.0.11            Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                   v6.0.12            Eases the creation of beautiful and testable command line interfaces
symfony/deprecation-contracts     v3.0.2             A generic function and convention to trigger deprecation notices
symfony/filesystem                v6.0.12            Provides basic utilities for the filesystem
symfony/finder                    v6.0.11            Finds files and directories via an intuitive fluent interface
symfony/options-resolver          v6.0.3             Provides an improved replacement for the array_replace PHP function
symfony/polyfill-ctype            v1.26.0            Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme    v1.26.0            Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer  v1.26.0            Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring         v1.26.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php81            v1.26.0            Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/service-contracts         v2.5.2             Generic abstractions related to writing services
symfony/string                    v6.0.12            Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme cl...
symfony/yaml                      v6.0.12            Loads and dumps YAML files
```

As you can see, neither `symfony/console` package was installed on version 5.2

**Comment by llaville** [comment]
One more check is : `composer why symfony/console` command that ouput on my side

```
bartlett/umlwriter dev-master requires  symfony/console (^4.4 || ^5.0 || ^6.0)
symfony/yaml       v6.0.12    conflicts symfony/console (<5.4)
```

**Comment by llaville** [comment]
There are new versions of `bartlett/box-manifest` (1.1.0), `bartlett/graph-uml` (1.3.0) available. Perharps it could solved your issue @MetalArend .

Anyway, as I've said, I cannot reproduced your problem, because I've no contextual source to run on !
I'll close this issue

**Comment by MetalArend** [comment]
I'll create a repository with the code parts mentioned above to reproduce this. This will happen again when there is an older and incompatible symfony/console version (as mentioned: symfony/console:v5.2.14 is one such example) in the project's dependencies, that does not play well with the expected symfony/console version for the tool itself. My guess would be that it has something to do with the way the classes from the project and the classes for the tool itself get autoloaded, and that the tool tries to run the tool's console command with the console classes that are available in the project.
